# GitLab user. git by default
user: git

# Url to gitlab instance. Used for api calls. Should be ends with slash.
gitlab_url: "https://{{ pillar.gitlab.server.server_name }}/"

http_settings:
#  user: someone
#  password: somepass
  self_signed_cert: true

# Repositories path
# REPOS_PATH MUST NOT BE A SYMLINK!!!
repos_path: "/srv/gitlab/repositories"

# File used as authorized_keys for gitlab user
auth_file: "/srv/gitlab/.ssh/authorized_keys"

# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  host: 127.0.0.1
  port: 6379
  # socket: /tmp/redis.socket # Only define this if you want to use sockets
  namespace: resque:gitlab
